# Generated by Django 4.2.11 on 2026-02-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listly_app', '0003_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='listly_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username', to='listly_app.listly_user'),
        ),
    ]
