# Generated by Django 4.2.11 on 2026-02-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listly_app', '0004_listly_user_task_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='listly_app.listly_user'),
        ),
    ]
